version: '3.8'
services:
  ######################
  ### COMPANIES SERVICE
  ######################
  companies-service:
    image: companies/service
    build: ./companies-service
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - /usr/src/companies-service
      - /usr/src/companies-service/node_modules
    networks:
      - webapp-network
  ######################
  ### JOBS SERVICE
  ######################
  jobs-service:
    image: jobs/service
    build: ./jobs-service
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=3001
    ports:
      - 3001:3001
    volumes:
      - /usr/src/jobs-service
      - /usr/src/jobs-service/node_modules
    networks:
      - webapp-network
  ######################
  ### PROFILES SERVICE
  ######################
  profiles-service:
    image: profiles/service
    build: ./profiles-service
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=3002
    ports:
      - 3002:3002
    volumes:
      - /usr/src/profiles-service
      - /usr/src/profiles-service/node_modules
    networks:
      - webapp-network
  ######################
  ### USERS SERVICE
  ######################
  users-service:
    image: users/service
    build: ./users-service
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=3003
    ports:
      - 3003:3003
    volumes:
      - /usr/src/users-service
      - /usr/src/users-service/node_modules
    networks:
      - webapp-network
  ######################
  ### NGINX SERVICE
  ######################
  proxy:
    build: ./nginx
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - companies-service
      - jobs-service
      - profiles-service
      - users-service
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge
